% OFDM modulator:
% 0)Intialization
% 1)QAM16 modulation
% 2)S2P conversion
% 3)IFFT t
% 4)CP insertion

disp("OFDM Starting");
clc; clear all;
close all; % Closes figures generated by the previous excution

tic                     % start measuring processing time
%%%%%%%%%%%%%%%%%%%%%%%0)Initiation%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp("Intialization:");

testDataSize = 32; % Number of test data bits
disp("Test Data: ");
disp(testDataSize);

M =8; %Number of subcarriers or size of IIFT
disp("Number of subcariers: ");
disp(M);

%n=256; %Total number of bits to be transmitted at the transmitter
%block_size = 16; %Size of each OFDM block to add cyclic prefix
%cp_len = floor(0.1 * block_size); %Length of the cyclic prefix

testData = struct2array(load('TestSample.mat')); % Load test data in a vector format
disp("Sample data:")
disp(testData);

% Optional plots

%{
figure(1)
stem(testData);
grid on;
xlabel('Data Points'); ylabel('Amplitude')
title('Test Data ')
%}


disp("===================================================================");


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%1)16QAM Modulation%%%%%%%%%%%%%%%%%%%
disp("16QAM Modulation: ");

QAMModulatedData = qammod(testData, 16); % Modulate testData using 16QAM modulator
disp("QAM data:");
disp(QAMModulatedData);

xlswrite('QAMModulatedData.xlsx',real(QAMModulatedData), 'QAM', 'A1'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(QAMModulatedData), 'QAM', 'B1'); % Save imag QAM data to file

% Optional plots

%{
figure(2);
stem(QAMModulatedData);
title('16-QAM Modulation')
%}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%2)S2P Conversion%%%%%%%%%%%%%%%%%%%%
disp("S2P Conversion: ");

prallelModulatedData = reshape(QAMModulatedData, M, testDataSize/M); % 8x4 matrix
disp(prallelModulatedData);

% Save data top Excel
%{
xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 1)), 'QAMPrallel', 'A1'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 1)), 'QAMPrallel', 'B1'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 2)), 'QAMPrallel', 'D1'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 2)), 'QAMPrallel', 'E1'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 3)), 'QAMPrallel', 'G1'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 3)), 'QAMPrallel', 'H1'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 4)), 'QAMPrallel', 'J1'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 4)), 'QAMPrallel', 'K1'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 5)), 'QAMPrallel', 'M1'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 5)), 'QAMPrallel', 'N1'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 6)), 'QAMPrallel', 'P1'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 6)), 'QAMPrallel', 'Q1'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 7)), 'QAMPrallel', 'S1'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 7)), 'QAMPrallel', 'T1'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 8)), 'QAMPrallel', 'V1'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 8)), 'QAMPrallel', 'W1'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 9)), 'QAMPrallel', 'A10'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 9)), 'QAMPrallel', 'B10'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 10)), 'QAMPrallel', 'D10'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 10)), 'QAMPrallel', 'E10'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 11)), 'QAMPrallel', 'G10'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 11)), 'QAMPrallel', 'H10'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 12)), 'QAMPrallel', 'J10'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 12)), 'QAMPrallel', 'K10'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 13)), 'QAMPrallel', 'M10'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 13)), 'QAMPrallel', 'N10'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 14)), 'QAMPrallel', 'P10'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 14)), 'QAMPrallel', 'Q10'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 15)), 'QAMPrallel', 'S10'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 15)), 'QAMPrallel', 'T10'); % Save imag QAM data to file

xlswrite('QAMModulatedData.xlsx',real(prallelModulatedData(:, 16)), 'QAMPrallel', 'V10'); % Save real QAM data to file
xlswrite('QAMModulatedData.xlsx',imag(prallelModulatedData(:, 16)), 'QAMPrallel', 'W10'); % Save imag QAM data to file
%}

% Optional Plots

%{
Sub_carrier1 = prallelModulatedData(:,1)
Sub_carrier2 = prallelModulatedData(:,2)
Sub_carrier3 = prallelModulatedData(:,3)
Sub_carrier4 = prallelModulatedData(:,4)


figure(3);
subplot(4,1,1);
stem(Sub_carrier1)
title('Subcarrier1');
grid on;
subplot(4,1,2)
stem(Sub_carrier2)
title('Subcarrier2')
grid on;
subplot(4,1,3)
stem(Sub_carrier3)
title('Subcarrier3')
grid on;
subplot(4,1,4)
stem(Sub_carrier4)
title('Subcarrier4')

grid on;
%}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%3)IFFT%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for i = 1:(testDataSize/M)                                  
    ifftData(:,i) = ifft((prallelModulatedData(:,i)), 8);         % prefome IFFT on the parallelized data
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%4) Cyclic prefix insertion%%%%%%%%%%%%%%

for i = 1:(testDataSize/M)
   cyclicPrefix(1,i) = ifftData(M,i);                     
end
OFDM_data = vertcat(cyclicPrefix, ifftData)                       % find and append cyclic prefix to all OFDM symbols

OFDM_signal = reshape(OFDM_data, 1, 36)                           % Serializing data to be ready for transmission
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

toc % stop measuring processing time and report

% optional, saving OFDM data to excel file
%{
xlswrite('Test.xlsx',real(OFDM_data(:, 1)), 'OFDM', 'A1'); % Save real QAM data to file
xlswrite('Test.xlsx',imag(OFDM_data(:, 1)), 'OFDM', 'B1'); % Save imag QAM data to file

xlswrite('Test.xlsx',real(OFDM_data(:, 2)), 'OFDM', 'D1'); % Save real QAM data to file
xlswrite('Test.xlsx',imag(OFDM_data(:, 2)), 'OFDM', 'E1'); % Save imag QAM data to file

xlswrite('Test.xlsx',real(OFDM_data(:, 3)), 'OFDM', 'G1'); % Save real QAM data to file
xlswrite('Test.xlsx',imag(OFDM_data(:, 3)), 'OFDM', 'H1'); % Save imag QAM data to file

xlswrite('Test.xlsx',real(OFDM_data(:, 4)), 'OFDM', 'J1'); % Save real QAM data to file
xlswrite('Test.xlsx',imag(OFDM_data(:, 4)), 'OFDM', 'K1'); % Save imag QAM data to file
%}

% optional plots
% OFDM signal plot
%{
figure(6),plot(real(OFDM_signal));
xlabel('Time'); ylabel('Amplitude');
title('OFDM Signal');
grid on;
%}

